### ISSUE TITLE
Color customization of `spin_1()` and other spinners

### ISSUE THREAD

**Issue by GitHunter0** [JohnCoene/waiter#117]
Hi folks,

First, thank you for this incredibly useful package.

Is there a way to change the color of `spin_1()`?

**Comment by JohnCoene** [comment]
I'm very sorry this issue escaped me.

```css
.spinner--1 {
  color: red;
}
```

This should work, the HTML is here: https://github.com/JohnCoene/waiter/blob/1797663ee3f46d941ed31dc981d46e5db539613c/R/spinners.R#L644

**Comment by GitHunter0** [comment]
No problem @JohnCoene , thank you for the feedback!

I tried this in my .css but the spin_1() is still in the default white color, I don't know why...
```
.spinner--1 {
  color: red !important;
}
```

**Comment by JohnCoene** [comment]
Sorry, it's the border

```css
.spinner--1 {
  border-top: 2px solid red;
}
```
